In [19]:
#Importamos librerias a utilizar
import pandas as pd
import numpy 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler

allData = pd.read_csv("SpotifyTop100.csv") #Lee el csv

allData.drop_duplicates(inplace = True) #Borra valores duplicados

allData.dropna(inplace = True) #Borra los valores NaN

otherDF = pd.DataFrame(allData['top genre'].unique()) #Genera un df para observar las diferentes posibilidades de
#tipos de género
otherDF.columns = ["genre"] #Renombramos la columna

allData['top genre'].replace(otherDF['genre'].to_numpy(),otherDF.index.values,inplace = True) #Remplazamos los valores string del género y los cambiamos por números
allData['artist type'].replace(['Solo','Duo','Trio','Band/Group'],[1,2,3,4],inplace = True) #Cambia los valores del tipo de artista por tipo int
allData['pop'] = round(allData['pop']/10)
allData['pop'].replace([0,1,2],"Not popular",inplace = True)
allData['pop'].replace([3,4,5],"Known",inplace = True)
allData['pop'].replace([6,7,8],"Popular",inplace = True)
allData['pop'].replace([9,10],"Very popular",inplace = True)

scaler = MinMaxScaler()
allData['top genre'] = scaler.fit_transform(allData['top genre'].values.reshape(-1, 1))
allData.head()


title      artist  top genre  \
0                  STARSTRUKK (feat. Katy Perry)       3OH!3   0.000000   
1                    My First Kiss (feat. Ke$ha)       3OH!3   0.000000   
2                                I Need A Dollar  Aloe Blacc   0.007634   
3  Airplanes (feat. Hayley Williams of Paramore)       B.o.B   0.015267   
4              Nothin' on You (feat. Bruno Mars)       B.o.B   0.015267   

   year released       added    bpm  nrgy  dnce   dB  live   val    dur  \
0         2009.0  2022‑02‑17  140.0  81.0  61.0 -6.0  23.0  23.0  203.0   
1         2010.0  2022‑02‑17  138.0  89.0  68.0 -4.0  36.0  83.0  192.0   
2         2010.0  2022‑02‑17   95.0  48.0  84.0 -7.0   9.0  96.0  243.0   
3         2010.0  2022‑02‑17   93.0  87.0  66.0 -4.0   4.0  38.0  180.0   
4         2010.0  2022‑02‑17  104.0  85.0  69.0 -6.0   9.0  74.0  268.0   

   acous  spch      pop  top year  artist type  
0    0.0   6.0  Popular    2010.0            2  
1    1.0   8.0  Popular    2010.0            2  
2   20.0   3.0  Popular    2010.0            1  
3   11.0  12.0  Popular    2010.0            1  
4   39.0   5.0  Popular    2010.0            1

In [20]:

X = allData.drop(columns = ['pop','title','artist','added','live']) #Generamos nuestro df input para obtener si una canción será popular
y = allData['pop'] #Generamos un df output para entrenar al modelo


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state = 42) #Separa el dataset en 80% training y 20% test
X_train, X_test, y_train, y_test


model = DecisionTreeClassifier()
model.fit(X_train, y_train) #Entrenas al modelo


DecisionTreeClassifier()

In [21]:
predictions = model.predict(X_test) #Haces predicciones con el df de validación
predictions_training = model.predict(X_train)
score_training = accuracy_score(y_train, predictions_training)
score = accuracy_score(y_test, predictions) #Mides el accuracy de tu modelo
print(f"Score training: {score_training*100}%\nScore Validation: {score*100}%")

Score training: 100.0%
Score Validation: 78.0%


In [22]:
matriz = confusion_matrix(predictions , y_test)
print(matriz)

[[  2   8   0]
 [  4 151   6]
 [  1  25   3]]


In [ ]:
from sklearn.linear_model import Perceptron
clf = Perceptron(tol = le-3, random_state = 0)
clf.fit(X_train, y_train)
clf.score(X_train, y_train)